<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBO8Gaj3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBO8Gaj3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBO8Gaj3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBO8Gaj3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBO8Gaj3\App_KernelDevDebugContainer([
    'container.build_hash' => 'BO8Gaj3',
    'container.build_id' => '80d08fb9',
    'container.build_time' => 1665860460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBO8Gaj3');
